// flow-typed signature: d73fbbc33a43384cb750bd8c089482a2
// flow-typed version: <<STUB>>/eslint-config-algolia_v^10.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-algolia'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-algolia' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-algolia/rules' {
  declare module.exports: any;
}

declare module 'eslint-config-algolia/sample-project/index' {
  declare module.exports: any;
}

declare module 'eslint-config-algolia/sample-project/src/connect' {
  declare module.exports: any;
}

declare module 'eslint-config-algolia/sample-project/src/createStore' {
  declare module.exports: any;
}

declare module 'eslint-config-algolia/sample-project/src/Provider' {
  declare module.exports: any;
}

declare module 'eslint-config-algolia/sample-project/src/storeShape' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-algolia/index' {
  declare module.exports: $Exports<'eslint-config-algolia'>;
}
declare module 'eslint-config-algolia/index.js' {
  declare module.exports: $Exports<'eslint-config-algolia'>;
}
declare module 'eslint-config-algolia/rules.js' {
  declare module.exports: $Exports<'eslint-config-algolia/rules'>;
}
declare module 'eslint-config-algolia/sample-project/index.js' {
  declare module.exports: $Exports<'eslint-config-algolia/sample-project/index'>;
}
declare module 'eslint-config-algolia/sample-project/src/connect.js' {
  declare module.exports: $Exports<'eslint-config-algolia/sample-project/src/connect'>;
}
declare module 'eslint-config-algolia/sample-project/src/createStore.js' {
  declare module.exports: $Exports<'eslint-config-algolia/sample-project/src/createStore'>;
}
declare module 'eslint-config-algolia/sample-project/src/Provider.js' {
  declare module.exports: $Exports<'eslint-config-algolia/sample-project/src/Provider'>;
}
declare module 'eslint-config-algolia/sample-project/src/storeShape.js' {
  declare module.exports: $Exports<'eslint-config-algolia/sample-project/src/storeShape'>;
}
